#### las 5 restricciones, se debe verificar lo siguiente para los datos o se piede tiempo
    -Linealidad
    -Homocedasticidad
    -Normalidad multivariable
    -Independencias de los errores
    -Ausencia de multicolinealidad

In [130]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [122]:
datos = pd.read_csv("./50_Startups.csv")
x = datos.iloc[:,:-1].values
y = datos.iloc[:,4].values

In [172]:
dir(datos)

['Administration',
 'Profit',
 'State',
 'T',
 '_AXIS_ALIASES',
 '_AXIS_IALIASES',
 '_AXIS_LEN',
 '_AXIS_NAMES',
 '_AXIS_NUMBERS',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',


In [178]:
column_names = datos.columns

In [136]:
labelencoder_X = LabelEncoder()
x[:, 3] = labelencoder_X.fit_transform(x[:, 3])


In [152]:
x

array([[165349.2, 136897.8, 471784.1, 2],
       [162597.7, 151377.59, 443898.53, 0],
       [153441.51, 101145.55, 407934.54, 1],
       [144372.41, 118671.85, 383199.62, 2],
       [142107.34, 91391.77, 366168.42, 1],
       [131876.9, 99814.71, 362861.36, 2],
       [134615.46, 147198.87, 127716.82, 0],
       [130298.13, 145530.06, 323876.68, 1],
       [120542.52, 148718.95, 311613.29, 2],
       [123334.88, 108679.17, 304981.62, 0],
       [101913.08, 110594.11, 229160.95, 1],
       [100671.96, 91790.61, 249744.55, 0],
       [93863.75, 127320.38, 249839.44, 1],
       [91992.39, 135495.07, 252664.93, 0],
       [119943.24, 156547.42, 256512.92, 1],
       [114523.61, 122616.84, 261776.23, 2],
       [78013.11, 121597.55, 264346.06, 0],
       [94657.16, 145077.58, 282574.31, 2],
       [91749.16, 114175.79, 294919.57, 1],
       [86419.7, 153514.11, 0.0, 2],
       [76253.86, 113867.3, 298664.47, 0],
       [78389.47, 153773.43, 299737.29, 2],
       [73994.56, 122782.75, 30331

In [154]:
OneHotEncoder?

In [148]:
enc = OneHotEncoder()

In [213]:
datos[["State"]]

State
0     New York
1   California
2      Florida
3     New York
4      Florida
5     New York
6   California
7      Florida
8     New York
9   California
10     Florida
11  California
12     Florida
13  California
14     Florida
15    New York
16  California
17    New York
18     Florida
19    New York
20  California
21    New York
22     Florida
23     Florida
24    New York
25  California
26     Florida
27    New York
28     Florida
29    New York
30     Florida
31    New York
32  California
33     Florida
34  California
35    New York
36     Florida
37  California
38    New York
39  California
40  California
41     Florida
42  California
43    New York
44  California
45    New York
46     Florida
47  California
48    New York
49  California

0       New York
1     California
2        Florida
3       New York
4        Florida
5       New York
6     California
7        Florida
8       New York
9     California
10       Florida
11    California
12       Florida
13    California
14       Florida
15      New York
16    California
17      New York
18       Florida
19      New York
20    California
21      New York
22       Florida
23       Florida
24      New York
25    California
26       Florida
27      New York
28       Florida
29      New York
30       Florida
31      New York
32    California
33       Florida
34    California
35      New York
36       Florida
37    California
38      New York
39    California
40    California
41       Florida
42    California
43      New York
44    California
45      New York
46       Florida
47    California
48      New York
49    California
Name: State, dtype: object

In [214]:
#np.array(datos.iloc[:,3])

In [211]:
## a=enc.fit_transform(np.array(datos.iloc[:,3]).reshape(-1,1)).toarray()

In [165]:
#a=enc.fit_transform(x[:,3].reshape(-1, 1)).toarray()

In [233]:
datos_codificados

<50x3 sparse matrix of type '<class 'numpy.float64'>'
	with 50 stored elements in Compressed Sparse Row format>

In [234]:
datos_codificados=enc.fit_transform(datos[["State"]]).toarray()


In [235]:
one_hot_encoded_frame =  pd.DataFrame(datos_codificados, columns= enc.get_feature_names(['State']), dty)

In [236]:
one_hot_encoded_frame

State_California  State_Florida  State_New York
0                0.0            0.0             1.0
1                1.0            0.0             0.0
2                0.0            1.0             0.0
3                0.0            0.0             1.0
4                0.0            1.0             0.0
5                0.0            0.0             1.0
6                1.0            0.0             0.0
7                0.0            1.0             0.0
8                0.0            0.0             1.0
9                1.0            0.0             0.0
10               0.0            1.0             0.0
11               1.0            0.0             0.0
12               0.0            1.0             0.0
13               1.0            0.0             0.0
14               0.0            1.0             0.0
15               0.0            0.0             1.0
16               1.0            0.0             0.0
17               0.0            0.0             1.0
18               0.0            1.0             0.0
19               0.0            0.0             1.0
20               1.0            0.0             0.0
21               0.0            0.0             1.0
22               0.0            1.0             0.0
23               0.0            1.0             0.0
24               0.0            0.0             1.0
25               1.0            0.0             0.0
26               0.0            1.0             0.0
27               0.0            0.0             1.0
28               0.0            1.0             0.0
29               0.0            0.0             1.0
30               0.0            1.0             0.0
31               0.0            0.0             1.0
32               1.0            0.0             0.0
33               0.0            1.0             0.0
34               1.0            0.0             0.0
35               0.0            0.0             1.0
36               0.0            1.0             0.0
37               1.0            0.0             0.0
38               0.0            0.0             1.0
39               1.0            0.0             0.0
40               1.0            0.0             0.0
41               0.0            1.0             0.0
42               1.0            0.0             0.0
43               0.0            0.0             1.0
44               1.0            0.0             0.0
45               0.0            0.0             1.0
46               0.0            1.0             0.0
47               1.0            0.0             0.0
48               0.0            0.0             1.0
49               1.0            0.0             0.0

In [217]:
enc.get_feature_names(['State'])

array(['State_California', 'State_Florida', 'State_New York'],
      dtype=object)

In [179]:
pd.DataFrame?

In [187]:
column_names[:-1]

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'State'], dtype='object')

In [212]:
datos

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [189]:
pd.DataFrame(x,columns=column_names[:-1])

R&D Spend Administration Marketing Spend State
0     165349         136898          471784     2
1     162598         151378          443899     0
2     153442         101146          407935     1
3     144372         118672          383200     2
4     142107        91391.8          366168     1
5     131877        99814.7          362861     2
6     134615         147199          127717     0
7     130298         145530          323877     1
8     120543         148719          311613     2
9     123335         108679          304982     0
10    101913         110594          229161     1
11    100672        91790.6          249745     0
12   93863.8         127320          249839     1
13   91992.4         135495          252665     0
14    119943         156547          256513     1
15    114524         122617          261776     2
16   78013.1         121598          264346     0
17   94657.2         145078          282574     2
18   91749.2         114176          294920     1
19   86419.7         153514               0     2
20   76253.9         113867          298664     0
21   78389.5         153773          299737     2
22   73994.6         122783          303319     1
23   67532.5         105751          304769     1
24     77044        99281.3          140575     2
25   64664.7         139553          137963     0
26   75328.9         144136          134050     1
27   72107.6         127865          353184     2
28   66051.5         182646          118148     1
29   65605.5         153032          107138     2
30   61994.5         115641         91131.2     1
31   61136.4         152702         88218.2     2
32   63408.9         129220         46085.2     0
33   55493.9         103057          214635     1
34   46426.1         157694          210798     0
35     46014        85047.4          205518     2
36   28663.8         127056          201127     1
37   44069.9        51283.1          197029     0
38   20229.6        65947.9          185265     2
39   38558.5        82982.1          174999     0
40   28754.3         118546          172796     0
41   27892.9        84710.8          164471     1
42   23640.9        96189.6          148001     0
43   15505.7         127382         35534.2     2
44   22177.7         154806         28334.7     0
45   1000.23         124153         1903.93     2
46   1315.46         115816          297114     1
47         0         135427               0     0
48    542.05        51743.2               0     2
49         0         116984         45173.1     0

array([[165349.2, 136897.8, 471784.1, 2],
       [162597.7, 151377.59, 443898.53, 0],
       [153441.51, 101145.55, 407934.54, 1],
       [144372.41, 118671.85, 383199.62, 2],
       [142107.34, 91391.77, 366168.42, 1],
       [131876.9, 99814.71, 362861.36, 2],
       [134615.46, 147198.87, 127716.82, 0],
       [130298.13, 145530.06, 323876.68, 1],
       [120542.52, 148718.95, 311613.29, 2],
       [123334.88, 108679.17, 304981.62, 0],
       [101913.08, 110594.11, 229160.95, 1],
       [100671.96, 91790.61, 249744.55, 0],
       [93863.75, 127320.38, 249839.44, 1],
       [91992.39, 135495.07, 252664.93, 0],
       [119943.24, 156547.42, 256512.92, 1],
       [114523.61, 122616.84, 261776.23, 2],
       [78013.11, 121597.55, 264346.06, 0],
       [94657.16, 145077.58, 282574.31, 2],
       [91749.16, 114175.79, 294919.57, 1],
       [86419.7, 153514.11, 0.0, 2],
       [76253.86, 113867.3, 298664.47, 0],
       [78389.47, 153773.43, 299737.29, 2],
       [73994.56, 122782.75, 30331

In [166]:
a

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0

In [144]:
enc.transform?

In [140]:
dir(enc)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_check_X',
 '_check_n_features',
 '_compute_drop_idx',
 '_fit',
 '_get_feature',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_transform',
 '_validate_data',
 '_validate_keywords',
 'categories',
 'drop',
 'dtype',
 'fit',
 'fit_transform',
 'get_feature_names',
 'get_params',
 'handle_unknown',
 'inverse_transform',
 'set_params',
 'sparse',
 'transform']

In [137]:
onehotencoder = OneHotEncoder

array([[165349.2, 136897.8, 471784.1, 2],
       [162597.7, 151377.59, 443898.53, 0],
       [153441.51, 101145.55, 407934.54, 1],
       [144372.41, 118671.85, 383199.62, 2],
       [142107.34, 91391.77, 366168.42, 1],
       [131876.9, 99814.71, 362861.36, 2],
       [134615.46, 147198.87, 127716.82, 0],
       [130298.13, 145530.06, 323876.68, 1],
       [120542.52, 148718.95, 311613.29, 2],
       [123334.88, 108679.17, 304981.62, 0],
       [101913.08, 110594.11, 229160.95, 1],
       [100671.96, 91790.61, 249744.55, 0],
       [93863.75, 127320.38, 249839.44, 1],
       [91992.39, 135495.07, 252664.93, 0],
       [119943.24, 156547.42, 256512.92, 1],
       [114523.61, 122616.84, 261776.23, 2],
       [78013.11, 121597.55, 264346.06, 0],
       [94657.16, 145077.58, 282574.31, 2],
       [91749.16, 114175.79, 294919.57, 1],
       [86419.7, 153514.11, 0.0, 2],
       [76253.86, 113867.3, 298664.47, 0],
       [78389.47, 153773.43, 299737.29, 2],
       [73994.56, 122782.75, 30331

In [27]:
datos.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [118]:
for x in range(10000):
    datos["State"].unique()
datos["State"].unique()

array(['New York', 'California', 'Florida'], dtype=object)

In [117]:
for x in range(10000):
    set(datos["State"])
set(datos["State"])

{'California', 'Florida', 'New York'}

In [ ]:
#ojo con las variables dummy, solo tenemos que
#hacer variables para n-1 categorias por ejemplo


In [25]:
pd.to_pickle?

In [115]:
pd.read_csv?

In [26]:
dir(pd)

['BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int64Index',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt64Index',
 'UInt8Dtype',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_config',
 '_hashtable',
 '_is_numpy_dev',
 '_lib',
 '_libs',
 '_np_version_under1p14',
 '_np_version_under1p15',
 '_np_version_under1p16',
 '_np_version_under1p17',
 '_